# Generated by Django 5.0.4 on 2024-05-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='urlaubstage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='week_hours',
        ),
    ]
