# Generated by Django 5.0.4 on 2024-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='gehalt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='ueberstunden',
            field=models.DecimalField(blank=-1, decimal_places=2, max_digits=5),
        ),
    ]
