# Generated by Django 5.0.4 on 2024-05-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superadmin',
        ),
    ]
