# Generated by Django 5.0.4 on 2024-05-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0002_remove_customuser_job_title_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
