# Generated by Django 5.0.4 on 2024-04-30 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0002_mitarbeiter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
