# Generated by Django 4.2.13 on 2024-05-26 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0003_adresse_mitarbeiter_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsstunden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('pause', models.TimeField(default='01:00')),
                ('stunden', models.TimeField()),
                ('ueberstunden', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
