# Generated by Django 5.0.4 on 2024-05-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0003_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hr', 'HR'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
