# Generated by Django 5.0.4 on 2024-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0003_mitarbeiter_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
