# Generated by Django 4.2.13 on 2024-05-27 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0004_arbeitsstunden'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstunden',
            name='datum2',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
