# Generated by Django 5.0.4 on 2024-04-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0004_mitarbeiter_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
