# Generated by Django 5.0.4 on 2024-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0004_rename_is_admin_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='week_hours',
            field=models.IntegerField(choices=[(30, '30'), (35, '35'), (40, '40')], default=35),
        ),
    ]
