# Generated by Django 4.2.13 on 2024-05-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0005_arbeitsstunden_datum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='beginn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='datum2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ende',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='stunden',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.TimeField(default='00:00'),
        ),
    ]
