# Generated by Django 5.0.4 on 2024-05-03 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0005_mitarbeiter_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitarbeiter',
            old_name='passwort',
            new_name='password',
        ),
    ]
