# Generated by Django 4.2.13 on 2024-05-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0006_alter_arbeitsstunden_beginn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='datum2',
        ),
    ]
