# Generated by Django 5.0.4 on 2024-05-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0006_rename_passwort_mitarbeiter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='admin_tag',
        ),
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='hr_tag',
        ),
    ]
