# Generated by Django 4.2.13 on 2024-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0007_remove_arbeitsstunden_datum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
