# Generated by Django 5.0.4 on 2024-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0007_adresse_state_customuser_gender_customuser_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
