# Generated by Django 5.0.4 on 2024-05-11 11:02

import bbq_gmbh_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bbq_gmbh_app', '0008_alter_adresse_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='city',
            field=models.CharField(default='Default City', max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='state',
            field=models.CharField(default='Default State', max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='street',
            field=models.CharField(default='Default Street', max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='zip_code',
            field=models.CharField(default='Default Zip Code', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.ForeignKey(default=bbq_gmbh_app.models.get_default_adresse, on_delete=django.db.models.deletion.PROTECT, related_name='customuser', to='bbq_gmbh_app.adresse'),
        ),
    ]
