# Generated by Django 4.2.13 on 2024-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0008_alter_arbeitsstunden_ueberstunden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.TimeField(default='00:00'),
        ),
    ]
