# Generated by Django 4.2.13 on 2024-05-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0009_alter_arbeitsstunden_ueberstunden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Hr', 'HR'), ('Admin', 'Admin')], default='user', max_length=20),
        ),
    ]
