# Generated by Django 5.0.4 on 2024-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0010_alter_adresse_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
