# Generated by Django 4.2.13 on 2024-05-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0012_alter_arbeitsstunden_beginn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='beginn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ende',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='pause',
            field=models.TimeField(choices=[('01:00', '1:00'), ('00:45', '0:45'), ('00:30', '0:30'), ('00:15', '0:15'), ('00:00', '0:00')], default='01:00'),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='stunden',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.TimeField(default='00:00'),
        ),
    ]
