# Generated by Django 4.2.13 on 2024-05-30 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0013_alter_arbeitsstunden_beginn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='stunden',
            field=models.DurationField(default=datetime.timedelta(seconds=28800)),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
