# Generated by Django 4.2.13 on 2024-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0014_alter_arbeitsstunden_stunden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='stunden',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.TimeField(default='00:00'),
        ),
    ]
