# Generated by Django 4.2.13 on 2024-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0015_alter_arbeitsstunden_stunden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
