# Generated by Django 4.2.13 on 2024-06-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0016_mitarbeiter_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='pause',
        ),
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='stunden',
        ),
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='ueberstunden',
        ),
    ]
