# Generated by Django 4.2.13 on 2024-06-01 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0017_remove_arbeitsstunden_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstunden',
            name='arbeitszeitGes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='arbeitszeitTag',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='pause',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=3600), '1:00'), (datetime.timedelta(seconds=2700), '0:45'), (datetime.timedelta(seconds=1800), '0:30'), (datetime.timedelta(seconds=900), '0:15'), (datetime.timedelta(0), '0:00')], default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='wochenarbeitszeit',
            field=models.DurationField(choices=[(datetime.timedelta(days=1, seconds=57600), '40:00'), (datetime.timedelta(days=1, seconds=39600), '35:00'), (datetime.timedelta(days=1, seconds=21600), '30:00')], default=datetime.timedelta(days=1, seconds=57600)),
        ),
    ]
