# Generated by Django 4.2.13 on 2024-06-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0020_remove_arbeitsstunden_wochenarbeitszeit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='arbeitszeitGes',
        ),
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='ueberstunden',
        ),
    ]
