# Generated by Django 4.2.13 on 2024-06-04 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0021_remove_arbeitsstunden_arbeitszeitges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstunden',
            name='gleitzeitTag',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
