# Generated by Django 4.2.13 on 2024-06-05 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0022_arbeitsstunden_gleitzeittag'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstunden',
            name='arbeitszeitGes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='ueberstunden',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
