# Generated by Django 4.2.13 on 2024-06-06 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0023_arbeitsstunden_arbeitszeitges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsstunden',
            name='maxArbeitszeitTag',
        ),
        migrations.AddField(
            model_name='arbeitsstunden',
            name='averageArbeitszeit',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
