# Generated by Django 4.2.13 on 2024-06-06 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0024_remove_arbeitsstunden_maxarbeitszeittag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsstunden',
            name='maxArbeitszeitTag',
            field=models.DurationField(default=datetime.timedelta(seconds=36000)),
        ),
    ]
