# Generated by Django 4.2.13 on 2024-07-02 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0025_arbeitsstunden_maxarbeitszeittag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlaub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertraglicheUrlaubstage', models.IntegerField(default=0)),
                ('sonderurlaub', models.IntegerField(default=0)),
                ('resturlaub', models.IntegerField(default=0)),
                ('beginn', models.DateField()),
                ('ende', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('genehmigtVon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genehmigtVon', to=settings.AUTH_USER_MODEL)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
