# Generated by Django 4.2.13 on 2024-07-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0026_urlaub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlaub',
            old_name='status',
            new_name='statusUrlaub',
        ),
    ]
