# Generated by Django 4.2.13 on 2024-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbq_gmbh_app', '0028_alter_urlaub_vertraglicheurlaubstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlaub',
            name='beginn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlaub',
            name='ende',
            field=models.DateField(blank=True, null=True),
        ),
    ]
